### ISSUE TITLE
Make sure not to use an outdated rootfs

### ISSUE THREAD

**Issue by djmaze** [hypriot/image-builder-odroid-c1#11]
I had an old version of the rootfs tgz sitting in my working directory. When pulling the latest version and running `make sdimage`, the build had many errors related to the outdated rootfs.

As we are using a distinct version of the rootfs for building, I propose to just change the `ROOTFS_TAR_PATH` to include the rootfs version. So can be sure a new version will be downloaded for everyone as soon as we update the version in the build script.

**Comment by StefanScherer** [comment]
Good point. I've opened https://github.com/hypriot/os-rootfs/issues/15 to fix this upstream and then here for the downloads.
