### ISSUE TITLE
No HDMI output

### ISSUE THREAD

**Issue by djmaze** [hypriot/image-builder-odroid-c1#12]
The bootloader configuration does not enable the HDMI output. At least for me it doesn't work.

We should probably change that as most people won't have a UART kit for diagnosing problems.

**Comment by djmaze** [comment]
Seems to rather be a bug since it is enabled in `boot.ini`.

**Comment by al-sabr** [comment]
Same here for me, after having issues with connection to the board via SSH,
I have restarted the board with a keyboard on my TV via HDMI I could not check
what is the problem via the shell because nothing is displayed.

**Comment by docbobo** [comment]
@gdeverlant can you check if running the following command via ssh enables HDMI out for you?

```
sudo sh -c "echo 0 > /sys/devices/platform/mesonfb/graphics/fb1/blank"
```

**Comment by al-sabr** [comment]
Unfortunately it doesn't work ... tried it and tested it on the HD TV.

**Comment by docbobo** [comment]
Bummer. Do you know if other distributions work? The C1 is rather problematic when it comes to HDMI.

**Comment by al-sabr** [comment]
Wait a second in the boot.ini file I think that the settings are not correct.

**Comment by al-sabr** [comment]
No I have tried the different configurations and it still doesn't work.

**Comment by al-sabr** [comment]
Personally I don't care because I get 940 MB free without HDMI.
