### ISSUE TITLE
Update tools to "Barbossa"

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-odroid-c1#27]
- [ ] rename to hypriotos-odroid-c1-vX.X.X.img.zip
- [ ] update docker-compose
- [ ] update docker-machine
- [ ] update docker-engine
- [ ] update device-init
- [ ] install docker images for consul + swarm
- [ ] install cluster-lab
- [ ] check for a more up to date kernel > 3.10
- [ ] add FAT partition for flash / device-init

**Comment by docbobo** [comment]
@StefanScherer Is this issue still valid?

**Comment by StefanScherer** [comment]
I think we close this, you have done a big step forward.
