### ISSUE TITLE
After some time impossible to connect to board via SSH.

### ISSUE THREAD

**Issue by al-sabr** [hypriot/image-builder-odroid-c1#33]
After adding some container with docker via ssh I've restarted the board and I can't access it via SSH.

I don't know what is the problem with HypriotOS.

**Comment by docbobo** [comment]
Do you have reproducible steps? I've been running both C1 and C2 for well over a week, without seeing anything like that. 

What kind of containers were you running? How many?

**Comment by al-sabr** [comment]
It's probably because you don't heavy load your board with many containers.

I will try your last release with my setup to see if the problem persist.

I have made a backup of my docker and will inject it to your latest release.

**Comment by docbobo** [comment]
In that case, it might as well be the OOM killer that kills ```sshd``` - hard to tell without more insight. Please have a look at #12. If that works we have both a fix for HDMI and a better way to track down this problem.

**Comment by al-sabr** [comment]
Ok with your last release the problem doesn't persist anymore.

https://github.com/hypriot/image-builder-odroid-c1/releases/tag/v0.4.1

The problem happened with : https://github.com/hypriot/image-builder-odroid-c1/releases/tag/v0.3.2

**Comment by docbobo** [comment]
Good to know that it's fixed with 0.4.1.
