### ISSUE TITLE
How to change host name in HypriotOS for Odroid C1

### ISSUE THREAD

**Issue by al-sabr** [hypriot/image-builder-odroid-c1#36]
Good day everyone,

I would like to change the hostname of my boards and unfortunately it doesn't work,
I tried this tutorial and no success... am I missing something with hostname renaming?

[https://www.howtogeek.com/50631/how-to-change-your-linux-hostname-without-rebooting/](https://www.howtogeek.com/50631/how-to-change-your-linux-hostname-without-rebooting/)

**Comment by docbobo** [comment]
HypriotOS uses ```device-init``` for those things:

```
HypriotOS/arm64: pirate@black-pearl in ~
$ device-init
device-init allows you to configure various aspect of your devices.
This ranges from configuration as simple as setting a hostname to
more complex stuff as configuring WiFi access.

Usage:
  device-init [flags]
  device-init [command]

Available Commands:
  cluster-lab manage cluster-lab settings
  docker      This command allows to do Docker related stuff
  hostname    Set or show hostname
  wifi        set or show WiFi settings

Flags:
  -c, --config string[="/boot/device-init.yaml"]   config file (default is /boot/device-init.yaml)
  -h, --help                                       help for device-init

Use "device-init [command] --help" for more information about a command.
```

**Comment by al-sabr** [comment]
Ok I did this : 

sudo device-init hostname set "bambuserver.1"

It does the job but it is not permanent

When I restarted the device and the computer name is still black-pearl

**Comment by docbobo** [comment]
In that case, you should just manually edit ```/boot/device-init.yml```

**Comment by al-sabr** [comment]
Correct it seems to override everything from the beginning.

Now that I have commented the hostname line it is all working.

Thank you!

**Comment by georgkreimer** [comment]
FYI seems like it's "/boot/user-data" nowadays

**Comment by alexgorbatchev** [comment]
FYI seems lit it's `cloud-init` nowadays (not `device-init`)

**Comment by alexgorbatchev** [comment]
I finally found how to change host name on a running instance. These instructions worked for me: https://aws.amazon.com/premiumsupport/knowledge-center/linux-static-hostname-rhel7-centos7/

**Comment by pve** [comment]
Changing the hostname after flashing on hypriot on the raspberry. 
Editing /var/lib/cloud/instance/cloud-config.txt worked for me. 
This persists after reboot.

**Comment by pve** [comment]
Raspi-config worked for me. Also on hypriot.

**Comment by mkmojo** [comment]
> I finally found how to change host name on a running instance. These instructions worked for me: https://aws.amazon.com/premiumsupport/knowledge-center/linux-static-hostname-rhel7-centos7/

Confirmed that this works for me as well.
I have a cluster of pi 4, running HypriotOS.
