### ISSUE TITLE
Tutorial steps are not reproduceable

### ISSUE THREAD

**Issue by al-sabr** [hypriot/image-builder-odroid-c1#37]
Hi I'm trying to do the step by step of the following tutorial and it doesn't work quiet as expected:

[https://blog.hypriot.com/post/how-to-setup-rpi-docker-swarm/](https://blog.hypriot.com/post/how-to-setup-rpi-docker-swarm/)

I've created 2 devices and it seems that there is no password for root user so all the ssh things doesn't work.

I tried the password for **username** root **password** hypriot but it doesn't work.

I've read somewhere that the root account was removed ... is it true?

thanx

**Comment by firecyberice** [comment]
Please have a look at [FAQ](https://blog.hypriot.com/faq/) for credentials
